language: go

go:
  - 1.15.x

services:
  - docker

jobs:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64-graviton2
      virt: vm

before_script:
  - eval $(go env)
  - curl -L https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-${GOARCH} -o /tmp/bazel
  - chmod +x /tmp/bazel
  - sudo mv /tmp/bazel /usr/local/bin/bazel
  - curl -L https://go.kubebuilder.io/dl/2.3.1/linux/${GOARCH} | tar -xz -C /tmp/
  - sudo mv /tmp/kubebuilder_2.3.1_linux_${GOARCH} /usr/local/kubebuilder

deploy:
  - provider: script
    script: >
      docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" &&
      make push &&
      make manifest &&
      mv greeter-operator.yaml greeter-operator-${GOARCH}.yaml
    edge: true
    on:
      tags: true
  - provider: releases
    file_glob: true
    file: greeter-operator-*.yaml
    edge: true
    on:
      tags: true
