# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - run:
          name: Install bazel
          command: |
            curl -LO https://github.com/bazelbuild/bazelisk/releases/download/v1.7.5/bazelisk-linux-amd64
            chmod +x bazelisk-linux-amd64
            sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
      - run:
          name: Install deps
          command: |
            sudo apt-get update
            sudo apt-get install patch
      - run:
          name: Run tests
          command: make 
