name: build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          target: builder
          load: true

      - run: |
          ci_env=`bash <(curl -s https://codecov.io/env)`
          docker run $ci_env -e CI=true ${{ steps.docker_build.outputs.digest }} /bin/bash -c ' \
            go test -mod=readonly -race -coverprofile=coverage.txt -covermode=atomic ./... && \
            bash <(curl -s https://codecov.io/bash)'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          target: builder
          platforms: linux/arm64
          tags: builder
          load: true

      - run: docker run -e ETCD_UNSUPPORTED_ARCH=arm64 builder go test -mod=readonly ./...
