name: release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

      - uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          target: greeter_server
          platforms: linux/amd64,linux/arm64
          tags: fengye87/greeter_server:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          target: greeter_client
          platforms: linux/amd64,linux/arm64
          tags: fengye87/greeter_client:${{ steps.get_version.outputs.version }}
          push: true

      - uses: docker/build-push-action@v2
        with:
          file: build/Dockerfile
          target: greeter_operator
          platforms: linux/amd64,linux/arm64
          tags: fengye87/greeter_operator:${{ steps.get_version.outputs.version }}
          push: true

      - run: make manifest

      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}

      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: greeter-operator.yaml
          asset_name: greeter-operator.yaml
          asset_content_type: text/yaml
